# Generated by Django 5.0.4 on 2024-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=150)),
                ('color', models.TextField(max_length=150)),
                ('size', models.TextField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
