# Generated by Django 5.0.4 on 2024-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_style', '0002_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
