# Generated by Django 5.0.4 on 2024-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step_style', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
