# Generated by Django 5.0.4 on 2024-05-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step_style', '0008_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
