# Generated by Django 5.0.4 on 2024-05-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step_style', '0009_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
